### PR TITLE
Support compressed responses

### PR DESCRIPTION
**Pull request by jsudhakar-gdrx**
Uncompresses responses before parsing JSON.

Fixes https://github.com/StarpTech/apollo-datasource-http/issues/38

### CODE REVIEW

**Comment by StarpTech** [comment]
Hi @jsudhakar-gdrx thank you for the PR. I'm going to review it ASAP.

**Comment by JustinTRoss** [comment]
Hey @StarpTech 👋  - Any guess at when you'll have time to review?

**Review by StarpTech — APPROVED** [review]
LGTM

**Comment by StarpTech** [comment]
https://github.com/StarpTech/apollo-datasource-http/releases/tag/0.21.0

**Pull request merged**
