### PR TITLE
feat: make POST requests cacheable

### PR DESCRIPTION
**Pull request by dwrBad**
This PR is related to https://github.com/StarpTech/apollo-datasource-http/issues/19

It makes POST requests cacheable. Default behavior will still be the same – only GET requests will be cached. But you may manually overwrite `isRequestCacheable()` to define a default behaviour. Additionaly you should/must overwrite `onCacheKeyCalculation` to define an adequate caching key (including the body for example).

### CODE REVIEW

**Comment by StarpTech** [comment]
Hi @dwrBad thank you for the PR. Before I review this PR we need to wait for https://github.com/StarpTech/apollo-datasource-http/pull/26. Please update this branch after the merge.

**Comment by dwrBad** [comment]
Hi @StarpTech 
I adjusted the code to fix the behaviour with the changes from #26 and updated the branch.
Thank you for looking into it!

**Comment by llc1123** [comment]
+1 on this PR. LGTM.

**Review by StarpTech — APPROVED** [review]
LGTM

**Pull request merged**
